version: "2.3"

networks:
  default:
    external:
      name: ros-network

volumes:
  workspace:

services:

  master:
    image: ros:kinetic-ros-core-xenial
    container_name: ros_master
    init: true
    restart: always
    command: roscore
    expose:
      - 11311
    ports:
      - "11311:11311"

  xserver:
    #build: ./xserver
    image: wn1980/xserver-ros${TAG}
    container_name: ros_xserver
    init: true
    restart: unless-stopped
    #ipc: host
    security_opt:
      - seccomp:unconfined
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "6901:6901"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1m"
      retries: 20

  turtlebot2:
    # env_file:
    #   - .env
    #build: ./turtlebot2
    image: wn1980/turtlebot2-kinetic${TAG}
    container_name: ros_turtlebot2_kinetic
    #hostname: ros-ops
    init: true
    restart: unless-stopped
    #ipc: host
    security_opt:
      - seccomp:unconfined
    volumes_from:
      - xserver
    depends_on:
      - xserver
    privileged: true
    devices:
      - "/dev:/dev"
    volumes:
      - workspace:/workspace
      - ~/.gitconfig:/home/developer/.gitconfig
      - "/run/systemd:/run/systemd"
      - "/dev:/dev"
    environment:
      - DISPLAY=:1
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://master:11311
    ports:
      - "8008:8008"
